import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Row,
  Column,
  Img,
  Link,
  Heading,
  Text,
  Hr,
  Button,
  Preview,
} from "@react-email/components";
import { Markdown } from "@react-email/markdown";

interface VideoSummary {
  title: string;
  channelName: string;
  videoUrl: string;
  thumbnailUrl: string;
  summary: string;
}

interface SummaryEmailProps {
  summaries: VideoSummary[];
}

export default function SummaryEmail({ summaries }: SummaryEmailProps) {
  const previewText = `${summaries.length} video summary${summaries.length > 1 ? "ies" : ""} ready for you`;

  return (
    <Html lang="en">
      <Head />
      <Preview>{previewText}</Preview>
      <Body style={bodyStyle}>
        <Container style={containerStyle}>
          {/* Header */}
          <Section style={headerStyle}>
            <Heading style={h1Style}>Your Video Summaries</Heading>
            <Text style={introStyle}>
              Here {summaries.length === 1 ? "is" : "are"} your{" "}
              {summaries.length} video summary
              {summaries.length > 1 ? "ies" : ""}:
            </Text>
          </Section>

          {/* Video Summaries */}
          {summaries.map((video, index) => (
            <Section key={index} style={videoCardStyle}>
              <Row>
                {/* Thumbnail */}
                <Column style={thumbnailColumnStyle}>
                  <Link href={video.videoUrl}>
                    <Img
                      src={video.thumbnailUrl}
                      alt={video.title}
                      width={200}
                      height={112}
                      style={thumbnailStyle}
                    />
                  </Link>
                </Column>

                {/* Video Info */}
                <Column style={infoColumnStyle}>
                  <Link href={video.videoUrl} style={titleLinkStyle}>
                    <Heading as="h2" style={videoTitleStyle}>
                      {video.title}
                    </Heading>
                  </Link>
                  <Text style={channelStyle}>{video.channelName}</Text>
                  <Button href={video.videoUrl} style={watchButtonStyle}>
                    Watch Video
                  </Button>
                </Column>
              </Row>

              {/* Summary */}
              <Row>
                <Column>
                  <Heading as="h3" style={summaryHeadingStyle}>
                    Summary
                  </Heading>
                  <Markdown
                    markdownCustomStyles={{
                      h2: { fontSize: "16px", color: "#1a1a1a", marginTop: "16px" },
                      h3: { fontSize: "14px", color: "#1a1a1a", marginTop: "12px" },
                      p: { fontSize: "14px", lineHeight: "1.6", color: "#4a4a4a" },
                      ul: { paddingLeft: "20px" },
                      li: { fontSize: "14px", lineHeight: "1.6", color: "#4a4a4a" },
                      
                    }}
                    markdownContainerStyles={{
                      backgroundColor: "#f9f9f9",
                      padding: "16px",
                      borderRadius: "8px",
                      borderLeft: "4px solid #3b82f6",
                    }}
                  >
                    {video.summary}
                  </Markdown>
                </Column>
              </Row>

              {index < summaries.length - 1 && <Hr style={dividerStyle} />}
            </Section>
          ))}

          {/* Footer */}
          <Section style={footerStyle}>
            <Text style={footerTextStyle}>
              Generated by YouTube Transcript Summarizer
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

// Styles
const bodyStyle: React.CSSProperties = {
  backgroundColor: "#f6f9fc",
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
};

const containerStyle: React.CSSProperties = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "20px",
  maxWidth: "600px",
  borderRadius: "8px",
};

const headerStyle: React.CSSProperties = {
  textAlign: "center",
  padding: "20px 0",
};

const h1Style: React.CSSProperties = {
  color: "#1a1a1a",
  fontSize: "24px",
  fontWeight: "600",
  margin: "0 0 16px",
};

const introStyle: React.CSSProperties = {
  fontSize: "14px",
  color: "#6b7280",
  margin: "0",
};

const videoCardStyle: React.CSSProperties = {
  padding: "24px 0",
};

const thumbnailColumnStyle: React.CSSProperties = {
  width: "200px",
  verticalAlign: "top",
};

const thumbnailStyle: React.CSSProperties = {
  borderRadius: "8px",
  objectFit: "cover",
};

const infoColumnStyle: React.CSSProperties = {
  paddingLeft: "16px",
  verticalAlign: "top",
};

const titleLinkStyle: React.CSSProperties = {
  textDecoration: "none",
};

const videoTitleStyle: React.CSSProperties = {
  color: "#1a1a1a",
  fontSize: "18px",
  fontWeight: "600",
  margin: "0 0 8px",
  lineHeight: "1.3",
};

const channelStyle: React.CSSProperties = {
  fontSize: "14px",
  color: "#6b7280",
  margin: "0 0 12px",
};

const watchButtonStyle: React.CSSProperties = {
  backgroundColor: "#ef4444",
  color: "#ffffff",
  padding: "8px 16px",
  borderRadius: "6px",
  fontSize: "14px",
  fontWeight: "500",
  textDecoration: "none",
};

const summaryHeadingStyle: React.CSSProperties = {
  fontSize: "14px",
  fontWeight: "600",
  color: "#1a1a1a",
  margin: "16px 0 8px",
  textTransform: "uppercase",
  letterSpacing: "0.5px",
};

const dividerStyle: React.CSSProperties = {
  borderColor: "#e5e7eb",
  margin: "24px 0",
};

const footerStyle: React.CSSProperties = {
  textAlign: "center",
  padding: "20px 0 0",
};

const footerTextStyle: React.CSSProperties = {
  fontSize: "12px",
  color: "#9ca3af",
};
